config/routes.rb
Rails.application.routes.draw do
  resources :candidates

  get '/home' => 'home#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
 has_attached_file :cv
	validates_attachment_presence :cv
	validates_attachment_size :cv, :less_than => 5.megabytes
	validates_attachment_content_type :cv, :content_type => ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ]
	validates :name, :highest_degree, :specialization , :marks, :total_experience, :work_summary, :work_gap, :education_gap, :mobile , presence: true
	HIGHESTDEGREE = ['Select', 'Not Pursuing Graduation', 'B.Sc', 'B.Tech/B.E', 'Diploma', 'M.Tech', 'Other']  
	SPECIALIZATION = ['Select', 'Agriculture', 'Automobile', 'Aviation', 'Bio-Chemistry/Bio-Technology', 'Biomedical', 'Ceramics', 'Chemical', 'Civil', 'Computers ', 'Electrical', 'Electronics/Telecommunication', 'Energy', 'Environmental', 'Instrumentation', 'Marine', 'Mechanical', 'Metallurgy', 'Mineral', 'Mining', 'Nuclear' , 'Paint/Oil', 'Petroleum' , 'Plastics', 'Production/Industrial', 'Textile',  'Other Engineering', 'Other' ]
	
end


   

app/controllers/application_controller.rb
require 'net/http'
require 'json'
require 'uri'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def sendRequestToOrientDB(url)
    request = generateHTTPRequest(url)
    # request.body = requestBody
    puts "request", request
    response = @http.request(request)
    Rails.logger.info "#################################### ORIENT REPONSE ###########################################"
    Rails.logger.info response.code
    #Rails.logger.info response.body
    return parseResponse(response)
  end

  def generateHTTPRequest(url)
    uri = URI.parse(url)
    puts "uriii", uri.inspect
    @http = Net::HTTP.new(uri.host, uri.port)
    @http.use_ssl = true
    puts "<<<<<<<<<<<<<<<<",@http.inspect
    puts "::::::::::::",uri.request_uri
    request = Net::HTTP::Get.new(uri.request_uri)
    # puts "hhhhhhhhhhhhhhhhhh",request.inspect
    # if isUserAdmin
    #   password = Digest::MD5.hexdigest("TestDatabaseadmin")
    #   user = "TestDatabaseadmin"
    # else
    #   user = "root"
    #   password = "smriti"
    # # end
    # request.basic_auth(user, password)
    # request["Content-Type"] = "application/json"
    # puts "after auth", request.inspect
    return request
  end

  def parseResponse(response)
    # 401 Unautharized
    # 500 Internal Server Error
    # 400 Error in Code
    if response.code.to_i == 200 || response.code.to_i == 404
      puts "dsvjjjjjjjjjjjjjjjjjjjjjjjjh", response.body
      return response.body

    else
      # Rails.logger.error "Error Occured in Orientdb: #{response.code}: #{response.body}"
      # raise "Error Message #{response.code} #{response.body}"
    end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :highest_degree, :specialization, :marks, :total_experience, :work_summary, :work_gap, :education_gap, :mobile, :linkedin, :stackoverflow, :github, :cv)
    end
end

app/controllers/home_controller.rb
require 'uri'
require 'csv'
require 'json'

class HomeController < ApplicationController

	def index
		# puts "insde"
          # @response1 = github_details('smriti154')
          # puts ">>>>>>>>>>>.", @response1
		 # @response1 = HTTParty.get('https://github.com/smriti154')
		  # @response2 = HTTParty.get('https://api.stackexchange.com/2.2/users/22656?order=desc&sort=reputation&site=stackoverflow')

		  @response3 = HTTParty.get('https://infinite-headland-24892.herokuapp.com/todos')
		  puts "kkkkkkkkkk", @response3
		  # @response4 = HTTParty.get('https://twitter.com/smriti')
		  # job_posting = 'Senior Software Test Engineer Person should have very good hands on experience on Selenium. Person should have some experience on overall Selenium framework as well so that he is aware how the entire test automation process work on top of Selenium. Experience on Protractor test would be a plus. End to end automation experience. Person shoud be flexible to jump to do manual testing on need basis. Person may also need to guide junior manual QA.'
		  # @result = `python public/temp.py`
		  # puts ".....", @result
          # render :text => result
  #         @candidate = Candidate.find_by id: '12'
  #         puts "..............", @candidate.inspect
  # 		CSV.open("public/dataset.csv", "w") do |csv| #open new file for write
  # 			JSON.parse(File.open("public/text.json").read).each do |hash|
  #   	 		csv << hash.values
  # 			end
		# end

		
		# RubyPython.start
		# my_python_module = RubyPython.import('public/temp.py')
		# value = my_python_module.my_python_function().rubify
		# puts "..........", my_python_module
		# RubyPython.stop

		# result111 = `python public/temp.py /home/neeraj/Profile_View_3D/public/dataset.csv`
		# puts "..result111.777..", result111.class

	end

	def github_details(username)
		
    # response = HTTParty.get("https://api.stackexchange.com/2.2/users/:id?order=desc&sort=reputation&site=stackoverflow&id={username}")
	

    # users = HTTParty.get("https://api.github.com/users/#{username}/repos")
    # @options = { query: { username: username } }
      # puts "response from github", users.count
      # users.count
  end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for @candidate , :html => { :multipart => true } do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :highest_degree %><br>
    <%= f.select :highest_degree, Candidate::HIGHESTDEGREE %>
  </div>
  <div class="field">
    <%= f.label :specialization %><br>
    <%= f.select :specialization, Candidate::SPECIALIZATION %>
  </div>
  <div class="field">
    <%= f.label :marks %><br>
    <%= f.number_field :marks %>
  </div>
  <div class="field">
    <%= f.label :total_experience %><br>
    <%= f.number_field :total_experience %>
  </div>
  <div class="field">
    <%= f.label :work_summary %><br>
    <%= f.text_field :work_summary %>
  </div>
  <div class="field">
    <%= f.label :work_gap %><br>
    <%= f.number_field :work_gap %>
  </div>
  <div class="field">
    <%= f.label :education_gap %><br>
    <%= f.number_field :education_gap %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :stackoverflow %><br>
    <%= f.text_field :stackoverflow %>
  </div>
  <div class="field">
    <%= f.label :github %><br>
    <%= f.text_field :github %>
  </div>
  <div class="field">
    <%= f.label :upload_CV %><br>
    <%= f.file_field :cv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Highest degree</th>
      <th>Specialization</th>
      <th>Marks</th>
      <th>Total experience</th>
      <th>Work summary</th>
      <th>Work gap</th>
      <th>Education gap</th>
      <th>Mobile</th>
      <th>Linkedin</th>
      <th>Stackoverflow</th>
      <th>Github</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.highest_degree %></td>
        <td><%= candidate.specialization %></td>
        <td><%= candidate.marks %></td>
        <td><%= candidate.total_experience %></td>
        <td><%= candidate.work_summary %></td>
        <td><%= candidate.work_gap %></td>
        <td><%= candidate.education_gap %></td>
        <td><%= candidate.mobile %></td>
        <td><%= candidate.linkedin %></td>
        <td><%= candidate.stackoverflow %></td>
        <td><%= candidate.github %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Highest degree:</strong>
  <%= @candidate.highest_degree %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @candidate.specialization %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @candidate.marks %>
</p>

<p>
  <strong>Total experience:</strong>
  <%= @candidate.total_experience %>
</p>

<p>
  <strong>Work summary:</strong>
  <%= @candidate.work_summary %>
</p>

<p>
  <strong>Work gap:</strong>
  <%= @candidate.work_gap %>
</p>

<p>
  <strong>Education gap:</strong>
  <%= @candidate.education_gap %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @candidate.mobile %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @candidate.linkedin %>
</p>

<p>
  <strong>Stackoverflow:</strong>
  <%= @candidate.stackoverflow %>
</p>

<p>
  <strong>Github:</strong>
  <%= @candidate.github %>
</p>

 <iframe src="<%= @candidate.cv.url %>"></iframe>
<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- Article: https://paulrhayes.com/2009-07/animated-css3-cube-interface-using-3d-transforms/ -->
    <!-- Demo: https://paulrhayes.com/experiments/cube-3d/ -->
    <!-- Originally posted: 17th July 2009 -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>3D CSS cube, use arrow keys to rotate &mdash; Paul Hayes</title>
    <meta name="author" content="Paul Hayes" />
    <link rel="canonical" href="https://paulrhayes.com/experiments/cube-3d/" />
    <link rel="stylesheet" href="../experiment-styles.css" />

    <link rel="stylesheet" href="css/experiment.css" />
</head>
<body class="experiment">
    <div class="wrapper">
        <p class="learn">
            This is a demo, <a href="https://paulrhayes.com/2009-07/animated-css3-cube-interface-using-3d-transforms/">learn how it works</a>.
        </p>

<div id="experiment">
    <div id="cube">
        <div class="face one" style="overflow-y: scroll; overflow-x: scroll">
          <%= @response1 %>
            One face
        </div>
        <div class="face two" style="overflow-y: scroll; overflow-x: scroll">
          
            Up, down, left, right
        </div>
        <div class="face three" style="overflow-y: scroll;">
          
        </div>
        <div class="face four" style="overflow-y: scroll; overflow-x: scroll">
          
            New forms of navigation are fun.
        </div>
        <div class="face five" style="overflow-y: scroll; overflow-x: scroll">
             
            Rotating 3D cube
        </div>
        <div class="face six">

            <%= @result %>
        </div>
    </div>
</div>

    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script>
    alert("hi")
     var props = 'transform WebkitTransform MozTransform OTransform msTransform'.split(' '),
    prop,
    el = document.createElement('div');

for(var i = 0, l = props.length; i < l; i++) {
    if(typeof el.style[props[i]] !== "undefined") {
        prop = props[i];
        break;
    }
}

var xAngle = 0, yAngle = 0;
$('body').keydown(function(evt) {
    switch(evt.keyCode) {
        case 37: // left
            yAngle -= 90;
            break;

        case 38: // up
            xAngle += 90;
            evt.preventDefault();
            break;

        case 39: // right
            yAngle += 90;
            break;

        case 40: // down
            xAngle -= 90;
            evt.preventDefault();
            break;
    };
    document.getElementById('cube').style[prop] = "rotateX("+xAngle+"deg) rotateY("+yAngle+"deg)";
});
    </script>


    <style>
    
#experiment {
  -webkit-perspective: 800px;
  -webkit-perspective-origin: 50% 200px;
  -moz-perspective: 800px;
  -moz-perspective-origin: 50% 200px;
  perspective: 800px;
  perspective-origin: 50% 200px;
}

#cube {
  position: relative;
  margin: 100px auto;
  height: 400px;
  width: 400px;
  -webkit-transition: -webkit-transform 2s linear;
  -webkit-transform-style: preserve-3d;
  -moz-transition: -moz-transform 2s linear;
  -moz-transform-style: preserve-3d;
  transition: transform 2s linear;
  transform-style: preserve-3d;
}

.face {
  position: absolute;
  height: 406px;
  width: 406px;
  padding: 1px;
  background-color: rgba(50, 50, 50, 0.7);
  font-size: 27px;
  line-height: 1em;
  color: #fff;
  border: 1px solid #555;
  border-radius: 3px;
}

#cube .one  {
  -webkit-transform: rotateX(90deg) translateZ(200px);
  -moz-transform: rotateX(90deg) translateZ(200px);
  transform: rotateX(90deg) translateZ(200px);
}

#cube .two {
  -webkit-transform: translateZ(200px);
  -moz-transform: translateZ(200px);
  transform: translateZ(200px);
}

#cube .three {
  -webkit-transform: rotateY(90deg) translateZ(200px);
  -moz-transform: rotateY(90deg) translateZ(200px);
  transform: rotateY(90deg) translateZ(200px);
}

#cube .four {
  -webkit-transform: rotateY(180deg) translateZ(200px);
  -moz-transform: rotateY(180deg) translateZ(200px);
  transform: rotateY(180deg) translateZ(200px);
}

#cube .five {
  -webkit-transform: rotateY(-90deg) translateZ(200px);
  -moz-transform: rotateY(-90deg) translateZ(200px);
  transform: rotateY(-90deg) translateZ(200px);
}

#cube .six {
  -webkit-transform: rotateX(-90deg) rotate(180deg) translateZ(200px);
  -moz-transform: rotateX(-90deg) rotate(180deg) translateZ(200px);
  transform: rotateX(-90deg) rotate(180deg) translateZ(200px);
}
    </style>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProfileView3d</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "master" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>